import {COMMON_RECEIVED_EVENTS, COMMON_SEND_EVENTS } from "./common/common";
import {CLIENT_USER_APP_RECEIVED_EVENTS, CLIENT_USER_APP_SEND_EVENTS} from "./client-user-app/event-types";
import {GAME_SERVER_APP_RECEIVED_EVENTS, GAME_SERVER_APP_SEND_EVENTS} from "./game-server-app/event-types";

export const RECEIVED_EVENTS =  Object.assign({}, COMMON_RECEIVED_EVENTS, CLIENT_USER_APP_RECEIVED_EVENTS, GAME_SERVER_APP_RECEIVED_EVENTS);
export const SEND_EVENTS = Object.assign({}, COMMON_SEND_EVENTS, CLIENT_USER_APP_SEND_EVENTS, GAME_SERVER_APP_SEND_EVENTS);
